var author = "Toby";

var email = "tobypadilla@gmail.com"

var regularJs = function(x) { return x + 1; };

var bsString = "Hi, #{author} is inside a string!"

var $bsLine = <span><a href="mailto:#{email}">#{author}</a></span>;

var bsMultiLine = function(href, title) {
  return <div>
           <div>
             <a href="#x{href}">#{title}</a>
           </div>
         </div>;
};

var screenshot = "screenshot.png"

var $bsImg = <img src=#{screenshot} />;

// Shouldn't break

if (5 < 8) "lt test"

if (8 > 5) "gt test"
